version: '3'

services:
  db:
    container_name: warehousedb
    image: postgres:14.1
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "warehouse"
      POSTGRES_DB: "warehouse"
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./psql:/var/lib/postgresql/data
      - ./psql-scripts:/docker-entrypoint-initdb.d
