version: '3'

services:
  postgres:
    container_name: warehousedb
    image: postgres:14.1
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "warehouse"
      POSTGRES_DB: "warehouse"
      PGDATA: /var/lib/postgresql/data
    volumes:
      - warehousedb:/var/lib/postgresql/data
      - ./psql-scripts:/docker-entrypoint-initdb.d
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=default@user.it
      - PGADMIN_DEFAULT_PASSWORD=password
    depends_on:
      - postgres
    ports:
      - 5050:80
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  warehousedb:
